import type { RawModelData, ProviderPlugin } from '../../types.js';

const PRICING_PAGE = 'https://ai.google.dev/gemini-api/docs/pricing.md.txt?hl=zh-cn';

interface GoogleModel {
  modelId: string;
  name: string;
  description: string;
  contextSize?: number;
  priceInput?: number;
  priceOutput?: number;
  isFree: boolean;
  capabilities: string[];
  category: string;
}

const MODEL_DATA: GoogleModel[] = [
  {
    modelId: 'gemini-3.1-pro-preview',
    name: 'Gemini 3.1 Pro Preview',
    description: '最新性能、智力和可用性改进，支持多模态理解、代理能力和 vibe-coding',
    contextSize: 2000000,
    priceInput: 2.00,
    priceOutput: 12.00,
    isFree: false,
    capabilities: ['chat', 'text-generation', 'reasoning', 'agentic'],
    category: 'LLM',
  },
  {
    modelId: 'gemini-3.1-flash-lite-preview',
    name: 'Gemini 3.1 Flash-Lite Preview',
    description: '最具成本效益的模型，针对高容量代理任务、翻译和简单数据处理优化',
    contextSize: 1000000,
    priceInput: 0.25,
    priceOutput: 1.50,
    isFree: true,
    capabilities: ['chat', 'text-generation'],
    category: 'LLM',
  },
  {
    modelId: 'gemini-3.1-flash-live-preview',
    name: 'Gemini 3.1 Flash Live Preview',
    description: '低延迟音频到音频模型，优化实时对话、 acoustic nuance 检测',
    contextSize: 1000000,
    priceInput: 0.75,
    priceOutput: 4.50,
    isFree: true,
    capabilities: ['chat', 'text-generation', 'speech-recognition'],
    category: 'LLM',
  },
  {
    modelId: 'gemini-3.1-flash-image-preview',
    name: 'Gemini 3.1 Flash Image Preview',
    description: '为速度和效率设计的图像生成模型',
    contextSize: 1000000,
    priceInput: 0.50,
    priceOutput: 3.00,
    isFree: false,
    capabilities: ['chat', 'text-generation', 'image-generation'],
    category: 'Image',
  },
  {
    modelId: 'gemini-3.1-flash-tts-preview',
    name: 'Gemini 3.1 Flash TTS Preview',
    description: '3.1 Flash 文本转语音模型，优化价格性能比',
    priceInput: 1.00,
    priceOutput: 20.00,
    isFree: true,
    capabilities: ['speech-synthesis'],
    category: 'TTS',
  },
  {
    modelId: 'gemini-3-flash-preview',
    name: 'Gemini 3 Flash Preview',
    description: '为速度而构建的智能模型，结合前沿智能与卓越搜索',
    contextSize: 1000000,
    priceInput: 0.50,
    priceOutput: 3.00,
    isFree: true,
    capabilities: ['chat', 'text-generation', 'reasoning'],
    category: 'LLM',
  },
  {
    modelId: 'gemini-3-pro-image-preview',
    name: 'Gemini 3 Pro Image Preview',
    description: '原生图像生成模型，优化速度、灵活性和上下文理解',
    contextSize: 2000000,
    priceInput: 2.00,
    priceOutput: 12.00,
    isFree: false,
    capabilities: ['chat', 'text-generation', 'image-generation'],
    category: 'Image',
  },
  {
    modelId: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    description: '最先进的通用模型，擅长编码和复杂推理任务',
    contextSize: 1000000,
    priceInput: 1.25,
    priceOutput: 10.00,
    isFree: true,
    capabilities: ['chat', 'text-generation', 'reasoning', 'coding'],
    category: 'LLM',
  },
  {
    modelId: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    description: '首个混合推理模型，支持 1M token 上下文窗口和思考预算',
    contextSize: 1000000,
    priceInput: 0.30,
    priceOutput: 2.50,
    isFree: true,
    capabilities: ['chat', 'text-generation', 'reasoning'],
    category: 'LLM',
  },
  {
    modelId: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash-Lite',
    description: '最小且最具成本效益的模型，为规模化使用而构建',
    contextSize: 1000000,
    priceInput: 0.10,
    priceOutput: 0.40,
    isFree: true,
    capabilities: ['chat', 'text-generation'],
    category: 'LLM',
  },
  {
    modelId: 'gemini-2.5-flash-lite-preview-09-2025',
    name: 'Gemini 2.5 Flash-Lite Preview',
    description: '基于 Gemini 2.5 Flash Lite 优化成本效益、高吞吐量和高质量',
    contextSize: 1000000,
    priceInput: 0.10,
    priceOutput: 0.40,
    isFree: true,
    capabilities: ['chat', 'text-generation'],
    category: 'LLM',
  },
  {
    modelId: 'gemini-2.5-flash-native-audio-preview-12-2025',
    name: 'Gemini 2.5 Flash Native Audio',
    description: '原生音频模型，优化更高质量的音频输出',
    contextSize: 1000000,
    priceInput: 0.50,
    priceOutput: 2.00,
    isFree: true,
    capabilities: ['chat', 'text-generation', 'speech-synthesis'],
    category: 'Audio',
  },
  {
    modelId: 'gemini-2.5-flash-image',
    name: 'Gemini 2.5 Flash Image',
    description: '原生图像生成模型，优化速度、灵活性和上下文理解',
    contextSize: 1000000,
    priceInput: 0.30,
    priceOutput: 0.039,
    isFree: false,
    capabilities: ['chat', 'text-generation', 'image-generation'],
    category: 'Image',
  },
  {
    modelId: 'gemini-2.5-flash-preview-tts',
    name: 'Gemini 2.5 Flash Preview TTS',
    description: '2.5 Flash 文本转语音模型，优化价格性能比和低延迟',
    priceInput: 0.50,
    priceOutput: 10.00,
    isFree: true,
    capabilities: ['speech-synthesis'],
    category: 'TTS',
  },
  {
    modelId: 'gemini-2.5-pro-preview-tts',
    name: 'Gemini 2.5 Pro Preview TTS',
    description: '2.5 Pro 文本转语音模型，优化强大、低延迟语音生成',
    priceInput: 1.00,
    priceOutput: 20.00,
    isFree: false,
    capabilities: ['speech-synthesis'],
    category: 'TTS',
  },
  {
    modelId: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    description: '（已弃用，将于 2026 年 6 月 1 日关闭）',
    contextSize: 1000000,
    priceInput: 0.10,
    priceOutput: 0.40,
    isFree: true,
    capabilities: ['chat', 'text-generation'],
    category: 'LLM',
  },
  {
    modelId: 'gemini-2.0-flash-lite',
    name: 'Gemini 2.0 Flash-Lite',
    description: '（已弃用，将于 2026 年 6 月 1 日关闭）',
    contextSize: 1000000,
    priceInput: 0.075,
    priceOutput: 0.30,
    isFree: true,
    capabilities: ['chat', 'text-generation'],
    category: 'LLM',
  },
  {
    modelId: 'imagen-4.0-generate-001',
    name: 'Imagen 4',
    description: '最新图像生成模型，显著更好的文本渲染和整体图像质量',
    priceInput: 0.04,
    priceOutput: 0,
    isFree: false,
    capabilities: ['image-generation'],
    category: 'Image',
  },
  {
    modelId: 'imagen-4.0-ultra-generate-001',
    name: 'Imagen 4 Ultra',
    description: '最高质量图像生成',
    priceInput: 0.06,
    priceOutput: 0,
    isFree: false,
    capabilities: ['image-generation'],
    category: 'Image',
  },
  {
    modelId: 'imagen-4.0-fast-generate-001',
    name: 'Imagen 4 Fast',
    description: '快速图像生成',
    priceInput: 0.02,
    priceOutput: 0,
    isFree: false,
    capabilities: ['image-generation'],
    category: 'Image',
  },
  {
    modelId: 'veo-3.1-generate-preview',
    name: 'Veo 3.1',
    description: '最新视频生成模型',
    priceInput: 0.40,
    priceOutput: 0,
    isFree: false,
    capabilities: ['video-generation'],
    category: 'Video',
  },
  {
    modelId: 'veo-3.1-fast-generate-preview',
    name: 'Veo 3.1 Fast',
    description: '快速视频生成',
    priceInput: 0.10,
    priceOutput: 0,
    isFree: false,
    capabilities: ['video-generation'],
    category: 'Video',
  },
  {
    modelId: 'veo-3.0-generate-001',
    name: 'Veo 3.0',
    description: '稳定版视频生成模型',
    priceInput: 0.40,
    priceOutput: 0,
    isFree: false,
    capabilities: ['video-generation'],
    category: 'Video',
  },
  {
    modelId: 'veo-2.0-generate-001',
    name: 'Veo 2.0',
    description: '最先进的视频生成模型',
    priceInput: 0.35,
    priceOutput: 0,
    isFree: false,
    capabilities: ['video-generation'],
    category: 'Video',
  },
  {
    modelId: 'lyria-3-clip-preview',
    name: 'Lyria 3 Clip',
    description: '音乐生成模型（30秒）',
    priceInput: 0.04,
    priceOutput: 0,
    isFree: false,
    capabilities: ['audio-generation'],
    category: 'Audio',
  },
  {
    modelId: 'lyria-3-pro-preview',
    name: 'Lyria 3 Pro',
    description: '音乐生成模型（全曲）',
    priceInput: 0.08,
    priceOutput: 0,
    isFree: false,
    capabilities: ['audio-generation'],
    category: 'Audio',
  },
  {
    modelId: 'gemini-embedding-2',
    name: 'Gemini Embedding 2',
    description: '首个多模态嵌入模型，将文本、图像、视频、音频和 PDF 映射到统一嵌入空间',
    priceInput: 0.20,
    priceOutput: 0,
    isFree: true,
    capabilities: ['embeddings'],
    category: 'Embedding',
  },
  {
    modelId: 'gemini-embedding-001',
    name: 'Gemini Embedding',
    description: '纯文本嵌入模型',
    priceInput: 0.15,
    priceOutput: 0,
    isFree: true,
    capabilities: ['embeddings'],
    category: 'Embedding',
  },
  {
    modelId: 'gemini-robotics-er-1.6-preview',
    name: 'Gemini Robotics-ER 1.6 Preview',
    description: '思考模型，增强机器人理解物理世界并与之交互的能力',
    contextSize: 1000000,
    priceInput: 1.00,
    priceOutput: 5.00,
    isFree: true,
    capabilities: ['chat', 'text-generation', 'robotics'],
    category: 'Robotics',
  },
  {
    modelId: 'gemini-robotics-er-1.5-preview',
    name: 'Gemini Robotics-ER 1.5 Preview',
    description: '思考模型，增强机器人理解物理世界并与之交互的能力',
    contextSize: 1000000,
    priceInput: 0.30,
    priceOutput: 2.50,
    isFree: true,
    capabilities: ['chat', 'text-generation', 'robotics'],
    category: 'Robotics',
  },
  {
    modelId: 'gemini-2.5-computer-use-preview-10-2025',
    name: 'Gemini 2.5 Computer Use Preview',
    description: '计算机使用模型，优化构建浏览器控制代理',
    contextSize: 1000000,
    priceInput: 1.25,
    priceOutput: 10.00,
    isFree: false,
    capabilities: ['chat', 'text-generation', 'agentic'],
    category: 'Agent',
  },
  {
    modelId: 'gemma-4',
    name: 'Gemma 4',
    description: '轻量级、最先进的开放模型',
    contextSize: 1000000,
    isFree: true,
    capabilities: ['chat', 'text-generation'],
    category: 'LLM',
  },
];

async function fetchGoogleModels(): Promise<RawModelData[]> {
  console.log('[google] Parsing models from pricing documentation...');

  return MODEL_DATA.map((m) => {
    const isFlagship = /pro|ultra/i.test(m.modelId);
    return {
      vendor: 'google',
      modelId: `google/${m.modelId}`,
      name: m.name,
      description: `Google: ${m.description}`,
      contextSize: m.contextSize,
      priceInput: m.priceInput,
      priceOutput: m.priceOutput !== undefined && m.priceOutput > 0 ? m.priceOutput : undefined,
      priceCurrency: 'USD',
      isFree: m.isFree,
      freeKind: m.isFree ? 'rate-limited' : 'unknown',
      trialScope: m.isFree ? (isFlagship ? 'flagship' : 'fast') : 'none',
      capabilities: m.capabilities,
      metadata: {
        originalId: m.modelId,
        category: m.category,
        provider: 'google',
      },
    };
  });
}

export const fetchModels: ProviderPlugin = fetchGoogleModels;